/*
PowerStore REST API

Storage cluster REST API definition. ( For \"Try It Out\", use the cluster management IP address to load this swaggerui interface. )

API version: 4.1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

// VolumeGroupSnapshotResponse Unique identifier of the new snapshot volume.
type VolumeGroupSnapshotResponse struct {
	Id *string `json:"id,omitempty"`
}
