/*
PowerStore REST API

Storage cluster REST API definition. ( For \"Try It Out\", use the cluster management IP address to load this swaggerui interface. )

API version: 4.1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

// BondingTypeEnum Bond type: * System_Bond - Immutable default system bond. * User_Bond - User created LACP based link aggregation group.  Was added in version 2.0.0.0.
type BondingTypeEnum string

// List of BondingTypeEnum
const (
	BONDINGTYPEENUM_SYSTEM_BOND BondingTypeEnum = "System_Bond"
	BONDINGTYPEENUM_USER_BOND   BondingTypeEnum = "User_Bond"
)

// All allowed values of BondingTypeEnum enum
var AllowedBondingTypeEnumEnumValues = []BondingTypeEnum{
	"System_Bond",
	"User_Bond",
}

func (v *BondingTypeEnum) Value() string {
	return string(*v)
}
