/*
PowerStore REST API

Storage cluster REST API definition. ( For \"Try It Out\", use the cluster management IP address to load this swaggerui interface. )

API version: 4.1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

// HardwareLifecycleStateEnum Lifecycle state of the Hardware. Current values are:  * Uninitialized - System is starting up.  * Healthy - Hardware is healthy.  * Initializing - System is starting up.  * Failed - Hardware has failed.  * Disconnected - Hardware was removed from the system.  * Prepare_Failed - Transient state used during startup.  * Trigger_Update - Transient state used during startup.  * Empty - No hardware present in this location.  * Replaced - Hardware has been replaced.  * Prepare_Reset - Transient state used during reset.  Values was added in 3.5.0.0: Replaced, Prepare_Reset.
type HardwareLifecycleStateEnum string

// List of HardwareLifecycleStateEnum
const (
	HARDWARELIFECYCLESTATEENUM_UNINITIALIZED  HardwareLifecycleStateEnum = "Uninitialized"
	HARDWARELIFECYCLESTATEENUM_HEALTHY        HardwareLifecycleStateEnum = "Healthy"
	HARDWARELIFECYCLESTATEENUM_INITIALIZING   HardwareLifecycleStateEnum = "Initializing"
	HARDWARELIFECYCLESTATEENUM_FAILED         HardwareLifecycleStateEnum = "Failed"
	HARDWARELIFECYCLESTATEENUM_DISCONNECTED   HardwareLifecycleStateEnum = "Disconnected"
	HARDWARELIFECYCLESTATEENUM_PREPARE_FAILED HardwareLifecycleStateEnum = "Prepare_Failed"
	HARDWARELIFECYCLESTATEENUM_TRIGGER_UPDATE HardwareLifecycleStateEnum = "Trigger_Update"
	HARDWARELIFECYCLESTATEENUM_EMPTY          HardwareLifecycleStateEnum = "Empty"
	HARDWARELIFECYCLESTATEENUM_REPLACED       HardwareLifecycleStateEnum = "Replaced"
	HARDWARELIFECYCLESTATEENUM_PREPARE_RESET  HardwareLifecycleStateEnum = "Prepare_Reset"
)

// All allowed values of HardwareLifecycleStateEnum enum
var AllowedHardwareLifecycleStateEnumEnumValues = []HardwareLifecycleStateEnum{
	"Uninitialized",
	"Healthy",
	"Initializing",
	"Failed",
	"Disconnected",
	"Prepare_Failed",
	"Trigger_Update",
	"Empty",
	"Replaced",
	"Prepare_Reset",
}

func (v *HardwareLifecycleStateEnum) Value() string {
	return string(*v)
}
