/*
PowerStore REST API

Storage cluster REST API definition. ( For \"Try It Out\", use the cluster management IP address to load this swaggerui interface. )

API version: 4.1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

import (
	"time"
)

// FileSystemModify Parameters for the file system modify operation. Modify a filesystem settings, where {id} is the unique identifier of the filesystem instance to modify Please note that modifying any of the following filesystem settings while in production may interrupt clients I/Os:     - access_policy     - locking_policy     - folder_rename_policy     - is_smb_sync_writes_enabled     - is_smb_op_locks_enabled     - is_async_MTime_enabled     - file_events_publishing_mode     - smb_notify_on_change_dir_depth
type FileSystemModify struct {
	// Description of the file system. (255 UTF-8 characters).
	Description *string `json:"description,omitempty"`
	// Size, in bytes, presented to the host or end user. This can be used for both expand and shrink on a file system. Value is always rounded up to next MB.
	SizeTotal          *int64                            `json:"size_total,omitempty"`
	AccessPolicy       *FileSystemAccessPolicyEnum       `json:"access_policy,omitempty"`
	LockingPolicy      *FileSystemLockingPolicyEnum      `json:"locking_policy,omitempty"`
	FolderRenamePolicy *FileSystemFolderRenamePolicyEnum `json:"folder_rename_policy,omitempty"`
	// Indicates whether the synchronous writes option is enabled on the file system. Values are: * true - Synchronous writes option is enabled on the file system. * false - Synchronous writes option is disabled on the file system.
	IsSmbSyncWritesEnabled *bool `json:"is_smb_sync_writes_enabled,omitempty"`
	// Indicates whether opportunistic file locking is enabled on the file system. Values are: * true - Opportunistic file locking is enabled on the file system. * false - Opportunistic file locking is disabled on the file system.
	IsSmbOpLocksEnabled *bool `json:"is_smb_op_locks_enabled,omitempty"`
	// Indicates whether file access notifications are enabled on the file system. Values are: * true - File access notifications are enabled on the file system. * false - File access notifications on file access are disabled on the file system.
	IsSmbNotifyOnAccessEnabled *bool `json:"is_smb_notify_on_access_enabled,omitempty"`
	// Indicates whether notifications on file writes are enabled on the file system. Values are: * true - File writes notifications are enabled on the file system. * false - File writes notifications are disabled on the file system.
	IsSmbNotifyOnWriteEnabled *bool `json:"is_smb_notify_on_write_enabled,omitempty"`
	// Lowest directory level to which the enabled notifications apply, if any.
	SmbNotifyOnChangeDirDepth *int32 `json:"smb_notify_on_change_dir_depth,omitempty"`
	// Indicates whether notifications of changes to a directory file structure are enabled. Values are: * true - Change directory notifications are disabled. * false - Change directory notifications are enabled.
	IsSmbNoNotifyEnabled *bool `json:"is_smb_no_notify_enabled,omitempty"`
	// Indicates whether asynchronous MTIME is enabled on the file system or protocol snaps that are mounted writeable. Values are: * true - Asynchronous MTIME is enabled on the file system. * false - Asynchronous MTIME is disabled on the file system.
	IsAsyncMTimeEnabled *bool `json:"is_async_MTime_enabled,omitempty"`
	// Unique identifier of the protection policy applied to the file system. name:{name} can be used instead of {id}. For example: 'protection_policy_id':'name:policy_name'
	ProtectionPolicyId *string `json:"protection_policy_id,omitempty"`
	// Unique identifier of the File_Performance type policy applied to the file_system. If empty and there is no performance policy set for the parent nas_server, then no performance policy is governing the file_system.  name:{name} can be used instead of {id}. For example: 'performance_policy_id':'name:policy_name' Was added in version 4.1.0.0.
	PerformancePolicyId *string `json:"performance_policy_id,omitempty"`
	// Indicates whether quota is enabled. Quotas are not supported for read-only file systems. Default value for the grace period is set to infinite=-1 to match Windows' quota policy Values are: * true - Start tracking usages for all users on a file system or a quota tree, and user quota limits will be enforced. * false - Stop tracking usages for all users on a file system or a quota tree, and user quota limits will not be enforced.
	IsQuotaEnabled *bool `json:"is_quota_enabled,omitempty"`
	// Grace period of soft limits (seconds):  * -1: default: Infinite grace (Windows policy).  *  0: Use system default of 1 week.  * Positive: Grace period after which the soft limit is treated as a hard limit (seconds).
	GracePeriod *int32 `json:"grace_period,omitempty"`
	// Default hard limit of user quotas and tree quotas (bytes). The hard limit value is always rounded up to match the file system's physical block size. (0 means 'No limitation'. This value can be used to compute the amount of space consumed without limiting the space).
	DefaultHardLimit *int64 `json:"default_hard_limit,omitempty"`
	// Default soft limit of user quotas and tree quotas (bytes). Value is always rounded up to match the file system's physical block size. (0 means 'No limitation'.)
	DefaultSoftLimit *int64 `json:"default_soft_limit,omitempty"`
	// Time when the snapshot will expire. Use 1970-01-01T00:00:00.000Z to set expiration timestamp to null.
	ExpirationTimestamp      *time.Time                    `json:"expiration_timestamp,omitempty"`
	FileEventsPublishingMode *FileEventsPublishingModeEnum `json:"file_events_publishing_mode,omitempty"`
	FlrAttributes            *FlrModify                    `json:"flr_attributes,omitempty"`
	// Indicates whether a snapshot type filesystem is secure: * true - The snapshot is read-only and cannot be deleted until it has expired.   The expiration time of secure snapshot cannot be reduced and cannot be set to infinite.   The value of is_secure cannot be changed from true to false. * false - A normal snapshot.  Was added in version 4.1.0.0.
	IsSecure *bool `json:"is_secure,omitempty"`
}
