/*
PowerStore REST API

Storage cluster REST API definition. ( For \"Try It Out\", use the cluster management IP address to load this swaggerui interface. )

API version: 4.1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

// ClusterCreateAppliances Appliance configuration setting during cluster creation. Was added in version 2.0.0.0.
type ClusterCreateAppliances struct {
	// The link local address is a dynamically set local IPv4 address. It is unique to this appliance and is set by Zeroconf. Use the PowerStore Discovery Tool to get the link local addresses of available PowerStore appliances on the local subnet.
	LinkLocalAddress string `json:"link_local_address"`
	// The name of the new appliance. By default, the name is \"[cluster name]-appliance-[index number]\". The maximum size is 64 characters.
	Name                       *string                         `json:"name,omitempty"`
	DriveFailureToleranceLevel *DriveFailureToleranceLevelEnum `json:"drive_failure_tolerance_level,omitempty"`
}
