/*
PowerStore REST API

Storage cluster REST API definition. ( For \"Try It Out\", use the cluster management IP address to load this swaggerui interface. )

API version: 4.1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

// NfsExportInstance This resource type has queriable associations from file_system, datastore
type NfsExportInstance struct {
	// Unique id of the NFS Export.
	Id *string `json:"id,omitempty"`
	// Unique identifier of the file system on which the NFS Export was created.
	FileSystemId *string `json:"file_system_id,omitempty"`
	// NFS Export name.  This property supports case-insensitive filtering.
	Name *string `json:"name,omitempty"`
	// Local path to a location within the file system. With NFS, each export must have a unique local path. By default, the system exports the root of the file system (top-most directory) at the time the file system is created. This path specifies the unique location of the file system on the storage system. Before you can create additional exports within an NFS shared folder, you must create directories within it from a Linux/Unix host that is connected to the file system. After a directory has been created from a mounted host, you can create a corresponding export and set access permissions accordingly.
	Path *string `json:"path,omitempty"`
	// NFS Export description.
	Description   *string                     `json:"description,omitempty"`
	DefaultAccess *NFSExportDefaultAccessEnum `json:"default_access,omitempty"`
	MinSecurity   *NFSExportMinSecurityEnum   `json:"min_security,omitempty"`
	// (*Applies to NFS shares of VMware NFS storage resources.*) Default owner of the NFS Export associated with the datastore. Required if secure NFS enabled. For NFSv3 or NFSv4 without Kerberos, the default owner is root.
	NfsOwnerUsername *string `json:"nfs_owner_username,omitempty"`
	// Hosts with no access to the NFS export or its snapshots. Hosts can be entered by Hostname, IP addresses (IPv4, IPv6, IPv4/PrefixLength, IPv6/PrefixLenght, or IPv4/subnetmask), or Netgroups prefixed with @.
	NoAccessHosts []string `json:"no_access_hosts,omitempty"`
	// Hosts with read-only access to the NFS export and its snapshots. Hosts can be entered by Hostname, IP addresses (IPv4, IPv6, IPv4/PrefixLength, IPv6/PrefixLenght, or IPv4/subnetmask), or Netgroups prefixed with @.
	ReadOnlyHosts []string `json:"read_only_hosts,omitempty"`
	// Hosts with read-only and ready-only for root user access to the NFS Export and its snapshots. Hosts can be entered by Hostname, IP addresses (IPv4, IPv6, IPv4/PrefixLength, IPv6/PrefixLenght, or IPv4/subnetmask), or Netgroups prefixed with @.
	ReadOnlyRootHosts []string `json:"read_only_root_hosts,omitempty"`
	// Hosts with read and write access to the NFS export and its snapshots. Hosts can be entered by Hostname, IP addresses (IPv4, IPv6, IPv4/PrefixLength, IPv6/PrefixLenght, or IPv4/subnetmask), or Netgroups prefixed with @.
	ReadWriteHosts []string `json:"read_write_hosts,omitempty"`
	// Hosts with read and write and read and write for root user access to the NFS Export and its snapshots. Hosts can be entered by Hostname, IP addresses (IPv4, IPv6, IPv4/PrefixLength, IPv6/PrefixLenght, or IPv4/subnetmask), or Netgroups prefixed with @.
	ReadWriteRootHosts []string `json:"read_write_root_hosts,omitempty"`
	// Specifies the user ID of the anonymous account.
	AnonymousUID *int32 `json:"anonymous_UID,omitempty"`
	// Specifies the group ID of the anonymous account.
	AnonymousGID *int32 `json:"anonymous_GID,omitempty"`
	// If set, do not allow access to set SUID. Otherwise, allow access.
	IsNoSUID *bool `json:"is_no_SUID,omitempty"`
	// Localized message string corresponding to default_access
	DefaultAccessL10n *string `json:"default_access_l10n,omitempty"`
	// Localized message string corresponding to min_security
	MinSecurityL10n *string             `json:"min_security_l10n,omitempty"`
	FileSystem      *FileSystemInstance `json:"file_system,omitempty"`
	// This is the inverse of the resource type datastore association.
	Datastores []DatastoreInstance `json:"datastores,omitempty"`
}
