/*
PowerStore REST API

Storage cluster REST API definition. ( For \"Try It Out\", use the cluster management IP address to load this swaggerui interface. )

API version: 4.1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

// RemoteSnapshotStateEnum State of the remote_snapshot:  * Protected - Transfer of remote_snapshot to remote has completed.  * Deleting - The remote_snapshot is being deleted.  Was added in version 3.5.0.0.
type RemoteSnapshotStateEnum string

// List of RemoteSnapshotStateEnum
const (
	REMOTESNAPSHOTSTATEENUM_PROTECTED RemoteSnapshotStateEnum = "Protected"
	REMOTESNAPSHOTSTATEENUM_DELETING  RemoteSnapshotStateEnum = "Deleting"
)

// All allowed values of RemoteSnapshotStateEnum enum
var AllowedRemoteSnapshotStateEnumEnumValues = []RemoteSnapshotStateEnum{
	"Protected",
	"Deleting",
}

func (v *RemoteSnapshotStateEnum) Value() string {
	return string(*v)
}
