/*
PowerStore REST API

Storage cluster REST API definition. ( For \"Try It Out\", use the cluster management IP address to load this swaggerui interface. )

API version: 4.1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

// FileEventsPublisherInstance  Was added in version 3.0.0.0. This resource type has queriable associations from file_events_pool, nas_server
type FileEventsPublisherInstance struct {
	// Unique identifier of the file events publisher.
	Id *string `json:"id,omitempty"`
	// Unique name of the file events publisher.  This property supports case-insensitive filtering.
	Name *string `json:"name,omitempty"`
	// Whether or not the event publisher will publish events.
	IsEnabled *bool `json:"is_enabled,omitempty"`
	// Time interval to scan each CEPA server (in seconds) for online/offline status.
	Heartbeat *int32 `json:"heartbeat,omitempty"`
	// Timeout in milliseconds while attempting to send event to a CEPA server to determine that is offline.
	ConnectionTimeout *int32               `json:"connection_timeout,omitempty"`
	PostEventPolicy   *PostEventPolicyEnum `json:"post_event_policy,omitempty"`
	// Behavior when no configured file events servers respond. Values are: false - allow I/O to the file system to continue. true - deny I/O to the filesystem when an event cannot be published to any server.
	DenyAccessWhenAllServersOffline *bool `json:"deny_access_when_all_servers_offline,omitempty"`
	// Name of a Windows user allowing Events Publishing to connect to CEPA servers. To ensure that a secure connection (via Microsoft RPC protocol) is used disable HTTP by setting http_port to 0.
	Username *string `json:"username,omitempty"`
	// TCP port number used but the service to connect to the CEPA server(s) with HTTP. Default port number is 12228. Set this value to 0 to disable HTTP. When enabled, connection via HTTP is attempted first. If HTTP connection is disabled, or the connection fails, then connection through MSRPC is attempted if all CEPP server(s) are defined by FQDN. The SMB account of the NAS server in the AD Domain is used to make the connection via MSRPC. Note that HTTP connections should only be used on secure networks, as it is neither SSL nor authenticated.
	HttpPort *int32 `json:"http_port,omitempty"`
	// Flag indicates if the file events publisher is a replicated publisher.
	IsReplica *bool `json:"is_replica,omitempty"`
	// Localized message string corresponding to post_event_policy Was added in version 3.0.0.0.
	PostEventPolicyL10n *string `json:"post_event_policy_l10n,omitempty"`
	// List of the file_events_pools that are associated with this file_events_publisher.
	FileEventsPools []FileEventsPoolInstance `json:"file_events_pools,omitempty"`
	// List of the nas_servers that are associated with this file_events_publisher.
	NasServers []NasServerInstance `json:"nas_servers,omitempty"`
}
