/*
PowerStore REST API

Storage cluster REST API definition. ( For \"Try It Out\", use the cluster management IP address to load this swaggerui interface. )

API version: 4.1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

// FileEventsPublishingModeEnum State of the event notification services for all file systems of the NAS server. * None - File event notifications are disabled for this file system. * SMB_Only - SMB notifications are enabled for this file system. * NFS_Only - NFS notifications are enabled for this file system. * All - SMB and NFS notifications are enabled for this file system.  Was added in version 3.0.0.0.
type FileEventsPublishingModeEnum string

// List of FileEventsPublishingModeEnum
const (
	FILEEVENTSPUBLISHINGMODEENUM_NONE     FileEventsPublishingModeEnum = "None"
	FILEEVENTSPUBLISHINGMODEENUM_SMB_ONLY FileEventsPublishingModeEnum = "SMB_Only"
	FILEEVENTSPUBLISHINGMODEENUM_NFS_ONLY FileEventsPublishingModeEnum = "NFS_Only"
	FILEEVENTSPUBLISHINGMODEENUM_ALL      FileEventsPublishingModeEnum = "All"
)

// All allowed values of FileEventsPublishingModeEnum enum
var AllowedFileEventsPublishingModeEnumEnumValues = []FileEventsPublishingModeEnum{
	"None",
	"SMB_Only",
	"NFS_Only",
	"All",
}

func (v *FileEventsPublishingModeEnum) Value() string {
	return string(*v)
}
