/*
PowerStore REST API

Storage cluster REST API definition. ( For "Try It Out", use the cluster management IP address to load this swaggerui interface. )

API version: 4.4.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

// RecycleBinConfigModify Modify recycle bin configuration request.
type RecycleBinConfigModify struct {
	// Duration in days for items to remain in the recycle bin before automatic purging. Valid range is 0 to 30. A value of 0 indicates items expire immediately.
	ExpirationDuration *int32 `json:"expiration_duration,omitempty"`
}
