/*
PowerStore REST API

Storage cluster REST API definition. ( For \"Try It Out\", use the cluster management IP address to load this swaggerui interface. )

API version: 4.1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

// FileLDAPProtocolEnum Indicates whether the LDAP protocol uses SSL for secure network communication. SSL encrypts data over the network and provides message and server authentication. * LDAP - LDAP protocol without SSL. * LDAPS - (Default) LDAP protocol with SSL. When you enable LDAPS, make sure to specify the appropriate LDAPS port (usually port 636) and to upload an LDAPS trust certificate to the LDAP server.
type FileLDAPProtocolEnum string

// List of FileLDAPProtocolEnum
const (
	FILELDAPPROTOCOLENUM_LDAP  FileLDAPProtocolEnum = "LDAP"
	FILELDAPPROTOCOLENUM_LDAPS FileLDAPProtocolEnum = "LDAPS"
)

// All allowed values of FileLDAPProtocolEnum enum
var AllowedFileLDAPProtocolEnumEnumValues = []FileLDAPProtocolEnum{
	"LDAP",
	"LDAPS",
}

func (v *FileLDAPProtocolEnum) Value() string {
	return string(*v)
}
