/*
PowerStore REST API

Storage cluster REST API definition. ( For \"Try It Out\", use the cluster management IP address to load this swaggerui interface. )

API version: 4.1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

// ValidUpgradeInstance Additional hardware details that are specific to each hardware component upgrade. Was added in version 3.6.0.0.
type ValidUpgradeInstance struct {
	ModelName *HardwareModelTypeEnum `json:"model_name,omitempty"`
	// DPE description.
	Dpe *string `json:"dpe,omitempty"`
	// CPU Cores description.
	CpuCores *string `json:"cpu_cores,omitempty"`
	// Memory description.
	PhysicalMemory *string `json:"physical_memory,omitempty"`
	// Number of nvram drives required for upgrade.
	NvramDrivesRequired *int32 `json:"nvram_drives_required,omitempty"`
	// Localized message string corresponding to model_name Was added in version 3.6.0.0.
	ModelNameL10n *string `json:"model_name_l10n,omitempty"`
}
