/*
PowerStore REST API

Storage cluster REST API definition. ( For \"Try It Out\", use the cluster management IP address to load this swaggerui interface. )

API version: 4.1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

// VolumeGroupConfigureMetro Configure metro operation arguments. Was added in version 4.0.0.0.
type VolumeGroupConfigureMetro struct {
	// The remote system with which the metro relationship will be established. The remote system must support metro volumes.  name:{name} can be used instead of {id}. For example: 'remote_system_id':'name:remote_system_name'
	RemoteSystemId string `json:"remote_system_id"`
	// A specific remote system appliance to which the volume group will be assigned, if desired. By default, the system will choose an appropriate appliance based on space, load, and connectivity.
	RemoteApplianceId *string `json:"remote_appliance_id,omitempty"`
}
