/*
PowerStore REST API

Storage cluster REST API definition. ( For \"Try It Out\", use the cluster management IP address to load this swaggerui interface. )

API version: 4.1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

// ClusterCreatePhysicalSwitches Physical switch configuration setting during cluster creation. Was added in version 2.0.0.0.
type ClusterCreatePhysicalSwitches struct {
	// Name of physical switch.
	Name    string                    `json:"name"`
	Purpose PhysicalSwitchPurposeEnum `json:"purpose"`
	// Supported connections for a physical switch.
	Connections []ClusterCreatePhysicalSwitchConnection `json:"connections"`
}
