/*
PowerStore REST API

Storage cluster REST API definition. ( For \"Try It Out\", use the cluster management IP address to load this swaggerui interface. )

API version: 4.1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package clientgen

import (
	"time"
)

// LocationHistoryInstance Storage resource location history. All entries are kept indefinitely and are removed when the resource object is deleted.
type LocationHistoryInstance struct {
	// Unique identifier of the appliance from which the volume was relocated.
	FromApplianceId *string `json:"from_appliance_id,omitempty"`
	// Unique identifier of the appliance to which the volume was relocated.
	ToApplianceId *string                    `json:"to_appliance_id,omitempty"`
	Reason        *LocationHistoryReasonEnum `json:"reason,omitempty"`
	// Time when the storage resource location changed.
	MigratedOn *time.Time `json:"migrated_on,omitempty"`
	// Localized message string corresponding to reason
	ReasonL10n *string `json:"reason_l10n,omitempty"`
}
